services:
  microusers:
    build: ./microusers
    links:
      - db
    depends_on:
      - db
      - consul
    ports:
      - "5002:5002"
    networks:
      - backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  microproducts:
    build: ./microproducts
    links:
      - db
    depends_on:
      - db
      - consul
    ports:
      - "5003:5003"
    networks:
      - backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  microorders:
    build: ./microorders 
    links:
      - db
    depends_on:
      - db
      - consul
    ports:
      - "5004:5004"
    networks:
      - backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    links:
      - microusers
      - microproducts
      - microorders
    depends_on:
      - consul
    ports:
      - "5001:5001"
    networks:
      - backend
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 5s
      retries: 3
  
  consul:
    build: ./consul
    ports:
      - "8500:8500"
    volumes:
      - ./consul/config:/consul/config
      - ./consul/scripts:/consul/scripts
    command: "agent -dev -config-dir=/consul/config -enable-script-checks -client=0.0.0.0"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  consul-init:
    image: curlimages/curl:latest
    depends_on:
      consul:
        condition: service_healthy
    volumes:
      - ./consul/scripts:/scripts
    command: ["/bin/sh", "/scripts/register-services.sh"]
    networks:
      - backend

networks:
  backend:

